version: '3'
services:
  nycunext:
    container_name: nycunext
    image: allen0hu/nycunext
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
  # Redis
  nycuredis:
    container_name: nycuredis
    image: allen0hu/nycuredis
    restart: unless-stopped
    tty: true
    # Port forwarding could be removed in production
    # Would still be able to connect between containers, but not from host.
    # ports: 
    #   - "6379:6379"
    volumes:
      - "nycuredis-cache:/data"
volumes:
  nycuredis-cache: